name: Publish on crates.io
on: 
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.ref }}"
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true
    - name: Cargo login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: -- ${{ secrets.CARGO_TOKEN }}
    - name: Publish relational_types_procmacro
      if: startsWith(github.ref, 'refs/tags/relational_types_procmacro-')
      uses: actions-rs/cargo@v1
      with:
        command: publish --dry-run
        args: --manifest-path relational_types_procmacro/Cargo.toml
    - name: Publish relational_types
      if: startsWith(github.ref, 'refs/tags/relational_types-')
      uses: actions-rs/cargo@v1
      with:
        command: publish --dry-run
